import { afterEach, describe, it } from "node:test"
import assert from "node:assert/strict"
import { JSDOM } from "jsdom"
import type { ChatMessage } from "./types"

// Regression guard for the per-turn model indicator: each assistant turn shows
// a `[model]` badge identifying which model generated it (msg.model, falling
// back to the session model for legacy history). Prior refactors silently broke
// nearby source-inspection tests; this behavioural test keeps the badge from
// disappearing unnoticed.

let cleanupDom: (() => void) | null = null

function installDom(): void {
  const dom = new JSDOM("<!doctype html><html><body></body></html>")
  const previous = {
    document: globalThis.document,
    window: globalThis.window,
    HTMLElement: globalThis.HTMLElement,
    HTMLDetailsElement: globalThis.HTMLDetailsElement,
    Node: globalThis.Node,
  }
  ;(globalThis as unknown as { document: Document }).document = dom.window.document
  ;(globalThis as unknown as { window: Window }).window = dom.window as unknown as Window
  ;(globalThis as unknown as { HTMLElement: typeof HTMLElement }).HTMLElement = dom.window.HTMLElement
  ;(globalThis as unknown as { HTMLDetailsElement: typeof HTMLDetailsElement }).HTMLDetailsElement = dom.window.HTMLDetailsElement
  ;(globalThis as unknown as { Node: typeof Node }).Node = dom.window.Node
  cleanupDom = () => {
    ;(globalThis as unknown as typeof previous).document = previous.document
    ;(globalThis as unknown as typeof previous).window = previous.window
    ;(globalThis as unknown as typeof previous).HTMLElement = previous.HTMLElement
    ;(globalThis as unknown as typeof previous).HTMLDetailsElement = previous.HTMLDetailsElement
    ;(globalThis as unknown as typeof previous).Node = previous.Node
    dom.window.close()
    cleanupDom = null
  }
}

function assistant(extra: Partial<ChatMessage>): ChatMessage {
  return {
    id: "a1",
    role: "assistant",
    sessionId: "s1",
    timestamp: Date.now(),
    blocks: [{ type: "text", text: "hi" }],
    ...extra,
  } as ChatMessage
}

afterEach(() => {
  cleanupDom?.()
})

describe("messageRenderer per-turn model badge", () => {
  it("shows the generating model on an assistant turn, provider prefix stripped", async () => {
    installDom()
    const { renderMessage } = await import("./messageRenderer")
    const el = renderMessage(assistant({ model: "anthropic/claude-sonnet-4-5" }))
    const badge = el.querySelector(".message-model-badge")
    assert.ok(badge, "assistant turn must render a model badge")
    assert.equal(badge!.textContent, "[claude-sonnet-4-5]", "badge shows the short model name")
    assert.equal(badge!.getAttribute("title"), "Model: anthropic/claude-sonnet-4-5", "tooltip carries the full id")
    assert.equal(badge!.getAttribute("aria-label"), "Generated by anthropic/claude-sonnet-4-5")
  })

  it("falls back to the session model when the message has no model of its own", async () => {
    installDom()
    const { renderMessage } = await import("./messageRenderer")
    const el = renderMessage(assistant({}), { sessionModel: "openai/gpt-5" } as Parameters<typeof renderMessage>[1])
    const badge = el.querySelector(".message-model-badge")
    assert.ok(badge, "badge must still render via the session-model fallback")
    assert.equal(badge!.textContent, "[gpt-5]")
  })

  it("does not render a model badge on user prompts", async () => {
    installDom()
    const { renderMessage } = await import("./messageRenderer")
    const el = renderMessage({
      id: "u1",
      role: "user",
      sessionId: "s1",
      timestamp: Date.now(),
      model: "anthropic/claude-sonnet-4-5",
      blocks: [{ type: "text", text: "hi" }],
    } as ChatMessage)
    assert.equal(el.querySelector(".message-model-badge"), null, "user turns must not show a model badge")
  })
})
