/**
 * Pure migration / merge helpers for unified session identity (ADR-007).
 *
 * These functions are intentionally vscode-free so they can be unit tested
 * directly. SessionStore wraps them with persistence and event emission.
 */

export interface MigratableSession {
  id: string
  name: string
  createdAt: number
  lastActiveAt: number
  model: string
  mode: string
  cliSessionId?: string
  pendingServerLink?: boolean
  needsBackfill?: boolean
  archived?: boolean
  messages: unknown[]
  cost: number
  tokenUsage: { prompt: number; completion: number; total: number }
  contextUsage?: {
    percent: number
    tokens: number
    maxTokens: number
    source?: "estimated" | "actual"
    updatedAt?: number
    breakdown?: {
      system: number
      history: number
      workspace: number
      queued?: number
      steer?: number
    }
    projected?: { withQueue: number; overflow: boolean }
    cost?: number
  }
  workspacePath?: string
  /** Set by migrateStalePlanModes when a pre-0.2.20 'plan' session is converted to 'build'. */
  modeMigratedAt?: number
}

export interface ServerSessionSnapshot {
  id: string
  title?: string
  time?: { updated?: number; created?: number }
  /** Set when this is a subagent (child) session spawned by a parent. */
  parentID?: string
  /** Working directory the session was created in (used for workspace scoping). */
  directory?: string
}

/**
 * Auto-generated names like "Session abcd1" or "Session 3" should be
 * overwritten when we learn a real title. User-entered names contain other
 * words and should be preserved.
 */
function isAutoGeneratedName(name: string): boolean {
  if (!name) return true
  return /^Session [A-Za-z0-9]{1,8}$/.test(name) || /^Session \d+$/.test(name)
}

export interface MigrationResult {
  rekeyed: number
  merged: number
}

export interface ImportResult {
  imported: number
  skipped: number
}

/**
 * ADR-014: the local map key is **immutable** for the life of a session. A solo
 * entry is **never** rekeyed to its `cliSessionId` — the server link lives only
 * in the `cliSessionId` field, and the key is shared verbatim with `TabManager`
 * and the webview. Rekeying it here (as ADR-007 did) divorced the store row from
 * its still-live tab and spawned duplicates.
 *
 * The only thing this still does is collapse **genuine legacy duplicates**: two
 * pre-ADR-014 rows that already resolve to the same `cliSessionId` (one
 * local-keyed, one server-keyed). The local row is merged into the surviving
 * server-keyed row and deleted. Mutates `bySessionId` in place.
 *
 * `MigrationResult.rekeyed` is retained in the shape for backwards compatibility
 * and is always `0`.
 */
export function migrateLocalIdsToServerIds(
  bySessionId: Map<string, MigratableSession>
): MigrationResult {
  let merged = 0
  const duplicates: Array<{ from: string; target: MigratableSession; sess: MigratableSession }> = []

  for (const [id, sess] of bySessionId) {
    if (!sess.cliSessionId) continue
    if (sess.cliSessionId === id) continue
    const target = bySessionId.get(sess.cliSessionId)
    // Only a DIFFERENT entry already keyed by the server id is a real duplicate.
    // A solo entry (no such target) is left untouched — its key is immutable.
    if (target && target !== sess) {
      duplicates.push({ from: id, target, sess })
    }
  }

  for (const { from, target, sess } of duplicates) {
    mergeSessionIntoTarget(target, sess)
    bySessionId.delete(from)
    merged++
  }

  return { rekeyed: 0, merged }
}

function mergeSessionIntoTarget(target: MigratableSession, source: MigratableSession): void {
  if ((target.name === "" || isAutoGeneratedName(target.name)) && source.name && !isAutoGeneratedName(source.name)) {
    target.name = source.name
  }
  if (source.messages.length > target.messages.length) target.messages = source.messages
  target.cost = Math.max(target.cost || 0, source.cost || 0)
  if (!target.contextUsage || ((source.contextUsage?.updatedAt ?? 0) > (target.contextUsage.updatedAt ?? 0))) {
    target.contextUsage = source.contextUsage
  }
  if (!target.model && source.model) target.model = source.model
  if (!target.workspacePath && source.workspacePath) target.workspacePath = source.workspacePath
  target.createdAt = Math.min(target.createdAt || source.createdAt, source.createdAt || target.createdAt)
  target.lastActiveAt = Math.max(target.lastActiveAt || 0, source.lastActiveAt || 0)
  target.cliSessionId = target.cliSessionId || source.cliSessionId
  if (!source.needsBackfill && source.messages.length > 0) delete target.needsBackfill
}

/**
 * Merge server-side session snapshots into the local map.
 *
 * Behavior per server session:
 *  - If `bySessionId` already contains the same id: skip (local wins; the
 *    cliSessionId is reaffirmed).
 *  - Otherwise: insert a new entry keyed by the server id, marked
 *    `needsBackfill: true` so the caller can lazily fetch full message
 *    history when the session is first activated.
 *
 * Returns the count of newly imported entries and the count of skipped
 * (already-known) entries.
 */
function syntheticName(id: string): string {
  const last = id.split("-").pop()
  return last ? `Session ${last}` : id
}

export function mergeServerSessions(
  bySessionId: Map<string, MigratableSession>,
  serverSessions: readonly ServerSessionSnapshot[],
  now: () => number = Date.now
): ImportResult {
  let imported = 0
  let skipped = 0

  for (const srv of serverSessions) {
    if (!srv?.id) {
      skipped++
      continue
    }
    // Subagent (child) sessions are spawned implicitly by the parent agent and
    // are not directly user-facing — opencode's own UI hides them. Skip both
    // the import and any reaffirmation so they never surface in the picker.
    if (srv.parentID) {
      skipped++
      continue
    }
    const existing = bySessionId.get(srv.id) ?? Array.from(bySessionId.values()).find((s) => s.cliSessionId === srv.id)
    if (existing) {
      // ADR-014: reaffirm the server link in the `cliSessionId` FIELD and sync
      // server-driven fields, but NEVER move or delete the map key. The local
      // key is immutable and shared with TabManager + the webview; rekeying it
      // here orphaned the live tab. Dedup is by `cliSessionId`, so no duplicate
      // row is created and no rekey is needed.
      if (!existing.cliSessionId) existing.cliSessionId = srv.id
      // Sync server-driven fields. We trust the server's title (it auto-titles
      // after the first user message) but never clobber a name the user has
      // explicitly customized — the auto-name regex tells the two apart.
      const serverTitle = srv.title?.trim()
      if (serverTitle && (existing.name === "" || isAutoGeneratedName(existing.name))) {
        existing.name = serverTitle
      } else if (!serverTitle && existing.name === "") {
        existing.name = syntheticName(srv.id)
      }
      if (srv.directory && !existing.workspacePath) {
        existing.workspacePath = srv.directory
      }
      const updatedAt = srv.time?.updated ?? srv.time?.created
      if (updatedAt && updatedAt > existing.lastActiveAt) {
        existing.lastActiveAt = updatedAt
      }
      skipped++
      continue
    }
    const updated = srv.time?.updated ?? srv.time?.created ?? now()
    const created = srv.time?.created ?? updated
    const entry: MigratableSession = {
      id: srv.id,
      // Empty when the server hasn't titled this session yet. Display layer
      // falls back to "Untitled session"; once we backfill messages the
      // first user prompt is used to derive a friendly title.
      name: srv.title?.trim() || syntheticName(srv.id),
      createdAt: created,
      lastActiveAt: updated,
      model: "",
      mode: "build",
      cliSessionId: srv.id,
      needsBackfill: true,
      messages: [],
      cost: 0,
      tokenUsage: { prompt: 0, completion: 0, total: 0 },
    }
    if (srv.directory) entry.workspacePath = srv.directory
    bySessionId.set(srv.id, entry)
    imported++
  }

  return { imported, skipped }
}

/**
 * Promote a session that was created offline (pendingServerLink=true) to be
 * keyed by a real server id. Mutates `bySessionId` in place.
 *
 * Returns false if the source is missing or the target id is already in use.
 */
/**
 * Migrate stale pre-0.2.20 sessions from `mode: "plan"` to `"build"`.
 *
 * Before v0.2.20 the harness defaulted new sessions to the opencode SDK's
 * default agent ("plan"). After v0.2.20 the explicit default is "build" (and
 * "plan" is a deliberate user choice). This migration converts every persisted
 * session whose mode is "plan" **and** has no `modeMigratedAt` timestamp.
 *
 * The `modeMigratedAt` guard makes the migration idempotent — a user who
 * deliberately picks plan mode after the fix keeps it.
 *
 * Mutates `bySessionId` in place. Returns the count of converted sessions.
 */
export function migrateStalePlanModes(
  bySessionId: Map<string, MigratableSession>
): { migrated: number } {
  const now = Date.now()
  let migrated = 0

  for (const sess of bySessionId.values()) {
    if (sess.mode === "plan" && sess.modeMigratedAt == null) {
      sess.mode = "build"
      sess.modeMigratedAt = now
      migrated++
    }
  }

  return { migrated }
}

export function promotePendingServerLink(
  bySessionId: Map<string, MigratableSession>,
  fromId: string,
  serverId: string
): boolean {
  if (!fromId || !serverId || fromId === serverId) return false
  const sess = bySessionId.get(fromId)
  if (!sess) return false
  if (bySessionId.has(serverId)) return false
  bySessionId.delete(fromId)
  sess.id = serverId
  sess.cliSessionId = serverId
  delete sess.pendingServerLink
  bySessionId.set(serverId, sess)
  return true
}
